#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG true

#define CHANNELS_COUNT 6

#define MASTER_CHANNEL_PIN_1 14
#define MASTER_CHANNEL_PIN_2 27
#define MASTER_CHANNEL_PIN_3 26
#define MASTER_CHANNEL_PIN_4 25
#define MASTER_CHANNEL_PIN_5 33
#define MASTER_CHANNEL_PIN_6 32

#define SLAVE_CHANNEL_PIN_1 2
#define SLAVE_CHANNEL_PIN_2 3
#define SLAVE_CHANNEL_PIN_3 4
#define SLAVE_CHANNEL_PIN_4 5
#define SLAVE_CHANNEL_PIN_5 6
#define SLAVE_CHANNEL_PIN_6 7

#define INTERRUPT_THRESHOLD_DELAY 25
#endif //Config.hpp