#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG true

#define CHANNELS_COUNT 6

#define MASTER_CHANNEL_PIN_1 0
#define MASTER_CHANNEL_PIN_2 2
#define MASTER_CHANNEL_PIN_3 14
#define MASTER_CHANNEL_PIN_4 12
#define MASTER_CHANNEL_PIN_5 13
#define MASTER_CHANNEL_PIN_6 15

#define SLAVE_CHANNEL_PIN_1 0
#define SLAVE_CHANNEL_PIN_2 0
#define SLAVE_CHANNEL_PIN_3 0
#define SLAVE_CHANNEL_PIN_4 0
#define SLAVE_CHANNEL_PIN_5 0
#define SLAVE_CHANNEL_PIN_6 0

#endif //Config.hpp